openapi: 3.1.0
info:
  title: openapi
  version: "1.0"
  contact:
    name: Johannes Polzer
    email: johannes.polzer@edu.szu.at
  description: API for ZELIA
servers:
  - url: "http://localhost:3000"
paths:
  /api/room:
    parameters: []
    get:
      summary: Get list of available rooms
      tags: []
      operationId: get-room-numbers
      parameters: []
      description: Get list of available rooms
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                description: ""
                type: array
                items:
                  type: string
  "/api/room/{roomNumber}/timetable":
    parameters:
      - schema:
          type: string
        name: roomNumber
        in: path
        required: true
    get:
      summary: Get room by room number
      operationId: get-room-room-number
      description: Get timetable by room Number
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ULesson"
components:
  schemas:
    UTeacher:
      description: ""
      type: object
      properties:
        id:
          type: number
        name:
          type: string
          minLength: 1
        longname:
          type: string
          minLength: 1
      required:
        - id
        - name
        - longname
      x-examples:
        example-1:
          id: 174
          name: ZACH
          longname: ZACHERL
    USubject:
      description: ""
      type: object
      properties:
        id:
          type: number
        name:
          type: string
          minLength: 1
        longname:
          type: string
          minLength: 1
      required:
        - id
        - name
        - longname
      x-examples:
        example-1:
          id: 496
          name: NWT1
          longname: Netzwerktechnik
    URoom:
      description: ""
      type: object
      properties:
        id:
          type: number
        name:
          type: string
          minLength: 1
        longname:
          type: string
          minLength: 1
      required:
        - id
        - name
        - longname
      x-examples:
        example-1:
          id: 305
          name: EDV 2406a
          longname: Teilungsraum zu EDV 2406 (vormals EDV6)
    ULesson:
      description: ""
      type: object
      x-examples:
        example-1:
          id: 1263062
          date: 20211018
          startTime: 1345
          endTime: 1435
          kl:
            - id: 973
              name: 3BHITN
              longname: HTL IT-NWTK
          te:
            - id: 174
              name: ZACH
              longname: ZACHERL
            - id: 221
              name: RESC
              longname: RESCH
          su:
            - id: 496
              name: NWT1
              longname: Netzwerktechnik
          ro:
            - id: 305
              name: EDV 2406a
              longname: Teilungsraum zu EDV 2406 (vormals EDV6)
          lsnumber: 72700
          activityType: Unterricht
      properties:
        id:
          type: number
        date:
          type: number
        startTime:
          type: number
        endTime:
          type: number
        kl:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            $ref: "#/components/schemas/UClass"
        te:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            $ref: "#/components/schemas/UTeacher"
        su:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            $ref: "#/components/schemas/USubject"
        ro:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            $ref: "#/components/schemas/URoom"
        lsnumber:
          type: number
        activityType:
          type: string
          minLength: 1
      required:
        - id
        - date
        - startTime
        - endTime
        - kl
        - te
        - su
        - ro
        - lsnumber
        - activityType
    UClass:
      description: ""
      type: object
      properties:
        id:
          type: number
        name:
          type: string
          minLength: 1
        longname:
          type: string
          minLength: 1
      required:
        - id
        - name
        - longname
      x-examples:
        example-1:
          id: 943
          name: 3AFITN
          longname: FS Informationstechnik (NWTK)
  parameters: {}
