openapi: 3.1.0
info:
  title: openapi
  version: "1.0"
  contact:
    name: Johannes Polzer
    email: johannes.polzer@edu.szu.at
  description: API for ZELIA
servers:
  - url: "http://localhost:3000"
paths:
  /api/room:
    parameters: []
    get:
      summary: Get list of available rooms
      tags: []
      operationId: get-room-numbers
      parameters: []
      description: Get list of available rooms
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/room"
  "/api/room/{roomNumber}":
    parameters:
      - schema:
          type: string
        name: roomNumber
        in: path
        required: true
    get:
      summary: Get room by room number
      operationId: get-room-room-number
      description: Get room by room number
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/room"
  /api/report:
    post:
      summary: Report an issue
      operationId: post-api-report
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/reportRequest"
      description: Report an issue
      responses:
        "200":
          description: OK
  /api/booking:
    post:
      summary: Book a room
      operationId: post-api-book
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bookingRequest"
      description: Book a room
  /api/admin/booking:
    get:
      summary: Get  bookings
      tags: []
      responses:
        "200":
          description: OK
      operationId: get-api-admin-booking
      description: Get bookings
      parameters:
        - $ref: "#/components/parameters/bookingType"
  /api/admin/report:
    get:
      summary: Get reports
      tags: []
      responses:
        "200":
          description: OK
      operationId: get-api-admin-report
      description: Get reports
      parameters:
        - $ref: "#/components/parameters/reportType"
components:
  schemas:
    room:
      title: room
      type: object
      properties:
        id:
          type: string
        roomNumber:
          $ref: "#/components/schemas/roomNumber"
      required:
        - roomNumber
    roomNumber:
      type: string
      title: roomNumber
      pattern: '^[A-Z][0-9]{3}(\.[0-9])?$'
      minLength: 5
      maxLength: 7
    reportRequest:
      title: reportRequest
      type: object
      properties:
        roomNumber:
          $ref: "#/components/schemas/roomNumber"
        description:
          type: string
        email:
          type: string
          format: email
      required:
        - roomNumber
        - description
        - email
    bookingRequest:
      title: bookingRequest
      type: object
      properties:
        id:
          type: string
  parameters:
    reportType:
      name: type
      in: query
      schema:
        type: string
        enum:
          - open
          - closed
          - in_progress
          - not_relevant
          - not_convertible
    bookingType:
      name: type
      in: query
      required: false
      schema:
        type: string
        enum:
          - open
          - closed
