version: "3"

services:
    nginx:
        image: nginx:1.16.0-alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./certs:/etc/certs
            - ./pwa/dist:/www
        ports:
            - "443:443"
        depends_on:
            - "api"
    api:
        build: ./api
    db:
        build: ./db
        volumes:
            - ./db/sql/01DatabaseScript.sql:/docker-entrypoint-initdb.d/01DatabaseScript.sql
