version: "3"

services:
    nginx:
        image: nginx:1.16.0-alpine
        volumes:
            - ./nginx-dev.conf:/etc/nginx/nginx.conf
            - ./certs:/etc/certs
        ports:
            - "443:443"
        depends_on:
            - "api"

    api:
        image: node:16-alpine
        volumes:
            - ./api:/src
        working_dir: /src
        command: ["npm", "run", "dev"]
    pwa:
        image: node:16-alpine
        volumes:
            - ./pwa:/src
        ports:
            - "3000:3000"
        working_dir: /src
        command: rm -r node_modules
        command: npm i
        command: ["npm", "run", "dev"]
    db:
        build: ./db
        volumes:
            - ./db/sql:/docker-entrypoint-initdb.d
