version: "3"

services:
    nginx:
        image: nginx:1.16.0-alpine
        volumes:
            - ./nginx-dev.conf:/etc/nginx/nginx.conf
            - ./certs:/etc/certs
        ports:
            - "443:443"
        depends_on:
            - "api"
    environment:
        PORT: 3001
        DB_SERVER: db
        DB_USER: root 
        DB_DATABASE: Zelia
        DB_PASSWORD_FILE: /api/apiSecrets/db_password
        WEBUNTIS_USERNAME_FILE: /api/apiSecrets/webuntis_username
        WEBUNTIS_PASSWORD_FILE: /api/apiSecrets/webuntis_password
        WEBUNTIS_SCHOOL: szu
        WEBUNTIS_BASE_URL: aoide.webuntis.com
    secrets:
        - DB_PASSWORD
        - WEBUNTIS_USERNAME
        - WEBUNTIS_PASSWORD
    api:
        image: node:16-alpine
        volumes:
            - ./api:/src
        working_dir: /src
        command: ["npm", "run", "dev"]
    pwa:
        image: node:16-alpine
        volumes:
            - ./pwa:/src
        ports:
            - "3000:3000"
        working_dir: /src
        command: rm -r node_modules
        command: npm i
        command: ["npm", "run", "dev"]
    db:
        build: ./db
        volumes:
            - ./db/sql:/docker-entrypoint-initdb.d
secrets:
  DB_PASSWORD:
    file: api/apiSecrets/db_password.txt
  WEBUNTIS_USERNAME:
    file: api/apiSecrets/webuntis_username.txt
  WEBUNTIS_PASSWORD:
    file: api/apiSecrets/webuntis_password.txt
