CREATE TABLE Room(
    Id INT NOT NULL AUTO_INCREMENT,
    AdminUserId INT NOT NULL,
    RoomNumber CHAR(30) NOT NULL,
    LongName CHAR(30) NOT NULL,
    RoomDescription VARCHAR(50) NOT NULL,
    RoomType VARCHAR(50) NOT NULL,
    IsWheelchairAccessable BOOL NOT NULL,
    HasWater BOOL NOT NULL,
    HasTeacherComputer BOOL NOT NULL,
    Projector VARCHAR(50) NOT NULL,
    ProjectorConnectors VARCHAR(50) NOT NULL,
    Boards VARCHAR(50) NOT NULL,
    NumberOfComputers INT NOT NULL,
    NumberOfSeats INT NOT NULL,
    CreatedAt DATETIME,
    UpdatedAt DATETIME,
    PRIMARY KEY(Id),
);